//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_BodegaLocal_Bebida", "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Bebida), "BodegaLocal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.BodegaLocal), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_detalle_venta_Bebida", "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Bebida), "detalle_venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.detalle_venta), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_detalle_venta_Venta1", "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Venta), "detalle_venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.detalle_venta), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_Venta_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Usuario), "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.Venta), true)]

#endregion

namespace Data_Access_Layer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BotilleriaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BotilleriaEntities object using the connection string found in the 'BotilleriaEntities' section of the application configuration file.
        /// </summary>
        public BotilleriaEntities() : base("name=BotilleriaEntities", "BotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BotilleriaEntities object.
        /// </summary>
        public BotilleriaEntities(string connectionString) : base(connectionString, "BotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BotilleriaEntities object.
        /// </summary>
        public BotilleriaEntities(EntityConnection connection) : base(connection, "BotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Bebida> Bebidas
        {
            get
            {
                if ((_Bebidas == null))
                {
                    _Bebidas = base.CreateObjectSet<Bebida>("Bebidas");
                }
                return _Bebidas;
            }
        }
        private ObjectSet<Bebida> _Bebidas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<BodegaLocal> BodegaLocals
        {
            get
            {
                if ((_BodegaLocals == null))
                {
                    _BodegaLocals = base.CreateObjectSet<BodegaLocal>("BodegaLocals");
                }
                return _BodegaLocals;
            }
        }
        private ObjectSet<BodegaLocal> _BodegaLocals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<detalle_venta> detalle_venta
        {
            get
            {
                if ((_detalle_venta == null))
                {
                    _detalle_venta = base.CreateObjectSet<detalle_venta>("detalle_venta");
                }
                return _detalle_venta;
            }
        }
        private ObjectSet<detalle_venta> _detalle_venta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Venta> Ventas
        {
            get
            {
                if ((_Ventas == null))
                {
                    _Ventas = base.CreateObjectSet<Venta>("Ventas");
                }
                return _Ventas;
            }
        }
        private ObjectSet<Venta> _Ventas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bebidas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBebidas(Bebida bebida)
        {
            base.AddObject("Bebidas", bebida);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the BodegaLocals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBodegaLocals(BodegaLocal bodegaLocal)
        {
            base.AddObject("BodegaLocals", bodegaLocal);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the detalle_venta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodetalle_venta(detalle_venta detalle_venta)
        {
            base.AddObject("detalle_venta", detalle_venta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ventas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVentas(Venta venta)
        {
            base.AddObject("Ventas", venta);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="Bebida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bebida : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Bebida object.
        /// </summary>
        /// <param name="id_producto">Initial value of the id_producto property.</param>
        /// <param name="nombre_producto">Initial value of the nombre_producto property.</param>
        /// <param name="precio">Initial value of the precio property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        /// <param name="grados_alcohol">Initial value of the grados_alcohol property.</param>
        /// <param name="volumen_litros">Initial value of the volumen_litros property.</param>
        public static Bebida CreateBebida(global::System.Int32 id_producto, global::System.String nombre_producto, global::System.Int32 precio, global::System.String tipo, global::System.Decimal grados_alcohol, global::System.Decimal volumen_litros)
        {
            Bebida bebida = new Bebida();
            bebida.id_producto = id_producto;
            bebida.nombre_producto = nombre_producto;
            bebida.precio = precio;
            bebida.tipo = tipo;
            bebida.grados_alcohol = grados_alcohol;
            bebida.volumen_litros = volumen_litros;
            return bebida;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_producto
        {
            get
            {
                return _id_producto;
            }
            set
            {
                if (_id_producto != value)
                {
                    Onid_productoChanging(value);
                    ReportPropertyChanging("id_producto");
                    _id_producto = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_producto");
                    Onid_productoChanged();
                }
            }
        }
        private global::System.Int32 _id_producto;
        partial void Onid_productoChanging(global::System.Int32 value);
        partial void Onid_productoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_producto
        {
            get
            {
                return _nombre_producto;
            }
            set
            {
                Onnombre_productoChanging(value);
                ReportPropertyChanging("nombre_producto");
                _nombre_producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_producto");
                Onnombre_productoChanged();
            }
        }
        private global::System.String _nombre_producto;
        partial void Onnombre_productoChanging(global::System.String value);
        partial void Onnombre_productoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Int32 _precio;
        partial void OnprecioChanging(global::System.Int32 value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal grados_alcohol
        {
            get
            {
                return _grados_alcohol;
            }
            set
            {
                Ongrados_alcoholChanging(value);
                ReportPropertyChanging("grados_alcohol");
                _grados_alcohol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("grados_alcohol");
                Ongrados_alcoholChanged();
            }
        }
        private global::System.Decimal _grados_alcohol;
        partial void Ongrados_alcoholChanging(global::System.Decimal value);
        partial void Ongrados_alcoholChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal volumen_litros
        {
            get
            {
                return _volumen_litros;
            }
            set
            {
                Onvolumen_litrosChanging(value);
                ReportPropertyChanging("volumen_litros");
                _volumen_litros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("volumen_litros");
                Onvolumen_litrosChanged();
            }
        }
        private global::System.Decimal _volumen_litros;
        partial void Onvolumen_litrosChanging(global::System.Decimal value);
        partial void Onvolumen_litrosChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_BodegaLocal_Bebida", "BodegaLocal")]
        public EntityCollection<BodegaLocal> BodegaLocals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BodegaLocal>("WebBotilleriaModel.FK_BodegaLocal_Bebida", "BodegaLocal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BodegaLocal>("WebBotilleriaModel.FK_BodegaLocal_Bebida", "BodegaLocal", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Bebida", "detalle_venta")]
        public EntityCollection<detalle_venta> detalle_venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Bebida", "detalle_venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Bebida", "detalle_venta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="BodegaLocal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BodegaLocal : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new BodegaLocal object.
        /// </summary>
        /// <param name="id_bodega">Initial value of the id_bodega property.</param>
        /// <param name="producto_fk">Initial value of the producto_fk property.</param>
        /// <param name="cantidad">Initial value of the cantidad property.</param>
        public static BodegaLocal CreateBodegaLocal(global::System.Int32 id_bodega, global::System.Int32 producto_fk, global::System.Int32 cantidad)
        {
            BodegaLocal bodegaLocal = new BodegaLocal();
            bodegaLocal.id_bodega = id_bodega;
            bodegaLocal.producto_fk = producto_fk;
            bodegaLocal.cantidad = cantidad;
            return bodegaLocal;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                if (_id_bodega != value)
                {
                    Onid_bodegaChanging(value);
                    ReportPropertyChanging("id_bodega");
                    _id_bodega = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bodega");
                    Onid_bodegaChanged();
                }
            }
        }
        private global::System.Int32 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int32 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 producto_fk
        {
            get
            {
                return _producto_fk;
            }
            set
            {
                Onproducto_fkChanging(value);
                ReportPropertyChanging("producto_fk");
                _producto_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("producto_fk");
                Onproducto_fkChanged();
            }
        }
        private global::System.Int32 _producto_fk;
        partial void Onproducto_fkChanging(global::System.Int32 value);
        partial void Onproducto_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_BodegaLocal_Bebida", "Bebida")]
        public Bebida Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("WebBotilleriaModel.FK_BodegaLocal_Bebida", "Bebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("WebBotilleriaModel.FK_BodegaLocal_Bebida", "Bebida").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bebida> BebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("WebBotilleriaModel.FK_BodegaLocal_Bebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bebida>("WebBotilleriaModel.FK_BodegaLocal_Bebida", "Bebida", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="detalle_venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class detalle_venta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new detalle_venta object.
        /// </summary>
        /// <param name="cantidad">Initial value of the cantidad property.</param>
        /// <param name="id_producto_fk">Initial value of the id_producto_fk property.</param>
        /// <param name="id_venta_fk">Initial value of the id_venta_fk property.</param>
        public static detalle_venta Createdetalle_venta(global::System.Int32 cantidad, global::System.Int32 id_producto_fk, global::System.Int32 id_venta_fk)
        {
            detalle_venta detalle_venta = new detalle_venta();
            detalle_venta.cantidad = cantidad;
            detalle_venta.id_producto_fk = id_producto_fk;
            detalle_venta.id_venta_fk = id_venta_fk;
            return detalle_venta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_producto_fk
        {
            get
            {
                return _id_producto_fk;
            }
            set
            {
                if (_id_producto_fk != value)
                {
                    Onid_producto_fkChanging(value);
                    ReportPropertyChanging("id_producto_fk");
                    _id_producto_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_producto_fk");
                    Onid_producto_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_producto_fk;
        partial void Onid_producto_fkChanging(global::System.Int32 value);
        partial void Onid_producto_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_venta_fk
        {
            get
            {
                return _id_venta_fk;
            }
            set
            {
                if (_id_venta_fk != value)
                {
                    Onid_venta_fkChanging(value);
                    ReportPropertyChanging("id_venta_fk");
                    _id_venta_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_venta_fk");
                    Onid_venta_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_venta_fk;
        partial void Onid_venta_fkChanging(global::System.Int32 value);
        partial void Onid_venta_fkChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Bebida", "Bebida")]
        public Bebida Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bebida> BebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Venta1", "Venta")]
        public Venta Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta1", "Venta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta1", "Venta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venta> VentaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta1", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta1", "Venta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id_usuario">Initial value of the id_usuario property.</param>
        /// <param name="nombre_usuario">Initial value of the nombre_usuario property.</param>
        /// <param name="contrasenja_usuario">Initial value of the contrasenja_usuario property.</param>
        /// <param name="esAdministrador">Initial value of the esAdministrador property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id_usuario, global::System.String nombre_usuario, global::System.String contrasenja_usuario, global::System.Boolean esAdministrador)
        {
            Usuario usuario = new Usuario();
            usuario.id_usuario = id_usuario;
            usuario.nombre_usuario = nombre_usuario;
            usuario.contrasenja_usuario = contrasenja_usuario;
            usuario.esAdministrador = esAdministrador;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_usuario
        {
            get
            {
                return _nombre_usuario;
            }
            set
            {
                Onnombre_usuarioChanging(value);
                ReportPropertyChanging("nombre_usuario");
                _nombre_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_usuario");
                Onnombre_usuarioChanged();
            }
        }
        private global::System.String _nombre_usuario;
        partial void Onnombre_usuarioChanging(global::System.String value);
        partial void Onnombre_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasenja_usuario
        {
            get
            {
                return _contrasenja_usuario;
            }
            set
            {
                Oncontrasenja_usuarioChanging(value);
                ReportPropertyChanging("contrasenja_usuario");
                _contrasenja_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasenja_usuario");
                Oncontrasenja_usuarioChanged();
            }
        }
        private global::System.String _contrasenja_usuario;
        partial void Oncontrasenja_usuarioChanging(global::System.String value);
        partial void Oncontrasenja_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean esAdministrador
        {
            get
            {
                return _esAdministrador;
            }
            set
            {
                OnesAdministradorChanging(value);
                ReportPropertyChanging("esAdministrador");
                _esAdministrador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("esAdministrador");
                OnesAdministradorChanged();
            }
        }
        private global::System.Boolean _esAdministrador;
        partial void OnesAdministradorChanging(global::System.Boolean value);
        partial void OnesAdministradorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Venta_Usuario", "Venta")]
        public EntityCollection<Venta> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("WebBotilleriaModel.FK_Venta_Usuario", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("WebBotilleriaModel.FK_Venta_Usuario", "Venta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="Venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Venta object.
        /// </summary>
        /// <param name="id_venta">Initial value of the id_venta property.</param>
        /// <param name="fecha">Initial value of the fecha property.</param>
        /// <param name="total_precio">Initial value of the total_precio property.</param>
        /// <param name="id_usuario_fk">Initial value of the id_usuario_fk property.</param>
        public static Venta CreateVenta(global::System.Int32 id_venta, global::System.DateTime fecha, global::System.Decimal total_precio, global::System.Int32 id_usuario_fk)
        {
            Venta venta = new Venta();
            venta.id_venta = id_venta;
            venta.fecha = fecha;
            venta.total_precio = total_precio;
            venta.id_usuario_fk = id_usuario_fk;
            return venta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_venta
        {
            get
            {
                return _id_venta;
            }
            set
            {
                if (_id_venta != value)
                {
                    Onid_ventaChanging(value);
                    ReportPropertyChanging("id_venta");
                    _id_venta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_venta");
                    Onid_ventaChanged();
                }
            }
        }
        private global::System.Int32 _id_venta;
        partial void Onid_ventaChanging(global::System.Int32 value);
        partial void Onid_ventaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal total_precio
        {
            get
            {
                return _total_precio;
            }
            set
            {
                Ontotal_precioChanging(value);
                ReportPropertyChanging("total_precio");
                _total_precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_precio");
                Ontotal_precioChanged();
            }
        }
        private global::System.Decimal _total_precio;
        partial void Ontotal_precioChanging(global::System.Decimal value);
        partial void Ontotal_precioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario_fk
        {
            get
            {
                return _id_usuario_fk;
            }
            set
            {
                Onid_usuario_fkChanging(value);
                ReportPropertyChanging("id_usuario_fk");
                _id_usuario_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_fk");
                Onid_usuario_fkChanged();
            }
        }
        private global::System.Int32 _id_usuario_fk;
        partial void Onid_usuario_fkChanging(global::System.Int32 value);
        partial void Onid_usuario_fkChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Venta1", "detalle_venta")]
        public EntityCollection<detalle_venta> detalle_venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Venta1", "detalle_venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Venta1", "detalle_venta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Venta_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
