//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("DAL", "FK_Bebida_MarcaBebida", "MarcaBebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.MarcaBebida), "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.Bebidas), true)]
[assembly: EdmRelationshipAttribute("DAL", "FK_Bebida_TipoBebida", "TipoBebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.TipoBebida), "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.Bebidas), true)]
[assembly: EdmRelationshipAttribute("DAL", "FK_BodegaLocal_Bebida", "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Bebidas), "BodegaLocal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.BodegaLocal), true)]
[assembly: EdmRelationshipAttribute("DAL", "FK_detalle_venta_Bebida", "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Bebidas), "detalle_venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.detalle_venta), true)]
[assembly: EdmRelationshipAttribute("DAL", "FK_detalle_venta_Venta", "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Venta), "detalle_venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.detalle_venta), true)]
[assembly: EdmRelationshipAttribute("DAL", "FK_Venta_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Usuario), "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.Venta), true)]

#endregion

namespace Data_Access_Layer
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class WebBotilleriaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto WebBotilleriaEntities usando la cadena de conexión encontrada en la sección 'WebBotilleriaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public WebBotilleriaEntities() : base("name=WebBotilleriaEntities", "WebBotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto WebBotilleriaEntities.
        /// </summary>
        public WebBotilleriaEntities(string connectionString) : base(connectionString, "WebBotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto WebBotilleriaEntities.
        /// </summary>
        public WebBotilleriaEntities(EntityConnection connection) : base(connection, "WebBotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Bebidas> Bebida
        {
            get
            {
                if ((_Bebida == null))
                {
                    _Bebida = base.CreateObjectSet<Bebidas>("Bebida");
                }
                return _Bebida;
            }
        }
        private ObjectSet<Bebidas> _Bebida;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<BodegaLocal> BodegaLocal
        {
            get
            {
                if ((_BodegaLocal == null))
                {
                    _BodegaLocal = base.CreateObjectSet<BodegaLocal>("BodegaLocal");
                }
                return _BodegaLocal;
            }
        }
        private ObjectSet<BodegaLocal> _BodegaLocal;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<detalle_venta> detalle_venta
        {
            get
            {
                if ((_detalle_venta == null))
                {
                    _detalle_venta = base.CreateObjectSet<detalle_venta>("detalle_venta");
                }
                return _detalle_venta;
            }
        }
        private ObjectSet<detalle_venta> _detalle_venta;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<MarcaBebida> MarcaBebida
        {
            get
            {
                if ((_MarcaBebida == null))
                {
                    _MarcaBebida = base.CreateObjectSet<MarcaBebida>("MarcaBebida");
                }
                return _MarcaBebida;
            }
        }
        private ObjectSet<MarcaBebida> _MarcaBebida;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<TipoBebida> TipoBebida
        {
            get
            {
                if ((_TipoBebida == null))
                {
                    _TipoBebida = base.CreateObjectSet<TipoBebida>("TipoBebida");
                }
                return _TipoBebida;
            }
        }
        private ObjectSet<TipoBebida> _TipoBebida;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Venta> Venta
        {
            get
            {
                if ((_Venta == null))
                {
                    _Venta = base.CreateObjectSet<Venta>("Venta");
                }
                return _Venta;
            }
        }
        private ObjectSet<Venta> _Venta;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Bebida. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBebida(Bebidas bebidas)
        {
            base.AddObject("Bebida", bebidas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet BodegaLocal. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBodegaLocal(BodegaLocal bodegaLocal)
        {
            base.AddObject("BodegaLocal", bodegaLocal);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet detalle_venta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTodetalle_venta(detalle_venta detalle_venta)
        {
            base.AddObject("detalle_venta", detalle_venta);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet MarcaBebida. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToMarcaBebida(MarcaBebida marcaBebida)
        {
            base.AddObject("MarcaBebida", marcaBebida);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet TipoBebida. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToTipoBebida(TipoBebida tipoBebida)
        {
            base.AddObject("TipoBebida", tipoBebida);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Venta. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVenta(Venta venta)
        {
            base.AddObject("Venta", venta);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="Bebidas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bebidas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Bebidas.
        /// </summary>
        /// <param name="id_bebida">Valor inicial de la propiedad id_bebida.</param>
        /// <param name="nombre_producto">Valor inicial de la propiedad nombre_producto.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        /// <param name="grados_alcohol">Valor inicial de la propiedad grados_alcohol.</param>
        /// <param name="volumen_litros">Valor inicial de la propiedad volumen_litros.</param>
        /// <param name="es_retornable">Valor inicial de la propiedad es_retornable.</param>
        /// <param name="comentario">Valor inicial de la propiedad comentario.</param>
        /// <param name="marca">Valor inicial de la propiedad marca.</param>
        public static Bebidas CreateBebidas(global::System.Int32 id_bebida, global::System.String nombre_producto, global::System.Double precio, global::System.Int32 tipo, global::System.Double grados_alcohol, global::System.Double volumen_litros, global::System.Boolean es_retornable, global::System.String comentario, global::System.Int32 marca)
        {
            Bebidas bebidas = new Bebidas();
            bebidas.id_bebida = id_bebida;
            bebidas.nombre_producto = nombre_producto;
            bebidas.precio = precio;
            bebidas.tipo = tipo;
            bebidas.grados_alcohol = grados_alcohol;
            bebidas.volumen_litros = volumen_litros;
            bebidas.es_retornable = es_retornable;
            bebidas.comentario = comentario;
            bebidas.marca = marca;
            return bebidas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bebida
        {
            get
            {
                return _id_bebida;
            }
            set
            {
                if (_id_bebida != value)
                {
                    Onid_bebidaChanging(value);
                    ReportPropertyChanging("id_bebida");
                    _id_bebida = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bebida");
                    Onid_bebidaChanged();
                }
            }
        }
        private global::System.Int32 _id_bebida;
        partial void Onid_bebidaChanging(global::System.Int32 value);
        partial void Onid_bebidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_producto
        {
            get
            {
                return _nombre_producto;
            }
            set
            {
                Onnombre_productoChanging(value);
                ReportPropertyChanging("nombre_producto");
                _nombre_producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_producto");
                Onnombre_productoChanged();
            }
        }
        private global::System.String _nombre_producto;
        partial void Onnombre_productoChanging(global::System.String value);
        partial void Onnombre_productoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Double _precio;
        partial void OnprecioChanging(global::System.Double value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.Int32 _tipo;
        partial void OntipoChanging(global::System.Int32 value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double grados_alcohol
        {
            get
            {
                return _grados_alcohol;
            }
            set
            {
                Ongrados_alcoholChanging(value);
                ReportPropertyChanging("grados_alcohol");
                _grados_alcohol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("grados_alcohol");
                Ongrados_alcoholChanged();
            }
        }
        private global::System.Double _grados_alcohol;
        partial void Ongrados_alcoholChanging(global::System.Double value);
        partial void Ongrados_alcoholChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double volumen_litros
        {
            get
            {
                return _volumen_litros;
            }
            set
            {
                Onvolumen_litrosChanging(value);
                ReportPropertyChanging("volumen_litros");
                _volumen_litros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("volumen_litros");
                Onvolumen_litrosChanged();
            }
        }
        private global::System.Double _volumen_litros;
        partial void Onvolumen_litrosChanging(global::System.Double value);
        partial void Onvolumen_litrosChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean es_retornable
        {
            get
            {
                return _es_retornable;
            }
            set
            {
                Ones_retornableChanging(value);
                ReportPropertyChanging("es_retornable");
                _es_retornable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("es_retornable");
                Ones_retornableChanged();
            }
        }
        private global::System.Boolean _es_retornable;
        partial void Ones_retornableChanging(global::System.Boolean value);
        partial void Ones_retornableChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comentario
        {
            get
            {
                return _comentario;
            }
            set
            {
                OncomentarioChanging(value);
                ReportPropertyChanging("comentario");
                _comentario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comentario");
                OncomentarioChanged();
            }
        }
        private global::System.String _comentario;
        partial void OncomentarioChanging(global::System.String value);
        partial void OncomentarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.Int32 _marca;
        partial void OnmarcaChanging(global::System.Int32 value);
        partial void OnmarcaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_Bebida_MarcaBebida", "MarcaBebida")]
        public MarcaBebida MarcaBebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MarcaBebida>("DAL.FK_Bebida_MarcaBebida", "MarcaBebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MarcaBebida>("DAL.FK_Bebida_MarcaBebida", "MarcaBebida").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MarcaBebida> MarcaBebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MarcaBebida>("DAL.FK_Bebida_MarcaBebida", "MarcaBebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MarcaBebida>("DAL.FK_Bebida_MarcaBebida", "MarcaBebida", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_Bebida_TipoBebida", "TipoBebida")]
        public TipoBebida TipoBebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoBebida>("DAL.FK_Bebida_TipoBebida", "TipoBebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoBebida>("DAL.FK_Bebida_TipoBebida", "TipoBebida").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoBebida> TipoBebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoBebida>("DAL.FK_Bebida_TipoBebida", "TipoBebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoBebida>("DAL.FK_Bebida_TipoBebida", "TipoBebida", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_BodegaLocal_Bebida", "BodegaLocal")]
        public EntityCollection<BodegaLocal> BodegaLocal
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<BodegaLocal>("DAL.FK_BodegaLocal_Bebida", "BodegaLocal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<BodegaLocal>("DAL.FK_BodegaLocal_Bebida", "BodegaLocal", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_detalle_venta_Bebida", "detalle_venta")]
        public EntityCollection<detalle_venta> detalle_venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalle_venta>("DAL.FK_detalle_venta_Bebida", "detalle_venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalle_venta>("DAL.FK_detalle_venta_Bebida", "detalle_venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="BodegaLocal")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BodegaLocal : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto BodegaLocal.
        /// </summary>
        /// <param name="id_bodega">Valor inicial de la propiedad id_bodega.</param>
        /// <param name="producto_fk">Valor inicial de la propiedad producto_fk.</param>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        public static BodegaLocal CreateBodegaLocal(global::System.Int32 id_bodega, global::System.Int32 producto_fk, global::System.Int32 cantidad)
        {
            BodegaLocal bodegaLocal = new BodegaLocal();
            bodegaLocal.id_bodega = id_bodega;
            bodegaLocal.producto_fk = producto_fk;
            bodegaLocal.cantidad = cantidad;
            return bodegaLocal;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                if (_id_bodega != value)
                {
                    Onid_bodegaChanging(value);
                    ReportPropertyChanging("id_bodega");
                    _id_bodega = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bodega");
                    Onid_bodegaChanged();
                }
            }
        }
        private global::System.Int32 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int32 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 producto_fk
        {
            get
            {
                return _producto_fk;
            }
            set
            {
                Onproducto_fkChanging(value);
                ReportPropertyChanging("producto_fk");
                _producto_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("producto_fk");
                Onproducto_fkChanged();
            }
        }
        private global::System.Int32 _producto_fk;
        partial void Onproducto_fkChanging(global::System.Int32 value);
        partial void Onproducto_fkChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                OncantidadChanging(value);
                ReportPropertyChanging("cantidad");
                _cantidad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidad");
                OncantidadChanged();
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_BodegaLocal_Bebida", "Bebida")]
        public Bebidas Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebidas>("DAL.FK_BodegaLocal_Bebida", "Bebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebidas>("DAL.FK_BodegaLocal_Bebida", "Bebida").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bebidas> BebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebidas>("DAL.FK_BodegaLocal_Bebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bebidas>("DAL.FK_BodegaLocal_Bebida", "Bebida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="detalle_venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class detalle_venta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto detalle_venta.
        /// </summary>
        /// <param name="cantidad">Valor inicial de la propiedad cantidad.</param>
        /// <param name="id_bebida_fk">Valor inicial de la propiedad id_bebida_fk.</param>
        /// <param name="id_venta_fk">Valor inicial de la propiedad id_venta_fk.</param>
        public static detalle_venta Createdetalle_venta(global::System.Int32 cantidad, global::System.Int32 id_bebida_fk, global::System.Int32 id_venta_fk)
        {
            detalle_venta detalle_venta = new detalle_venta();
            detalle_venta.cantidad = cantidad;
            detalle_venta.id_bebida_fk = id_bebida_fk;
            detalle_venta.id_venta_fk = id_venta_fk;
            return detalle_venta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bebida_fk
        {
            get
            {
                return _id_bebida_fk;
            }
            set
            {
                if (_id_bebida_fk != value)
                {
                    Onid_bebida_fkChanging(value);
                    ReportPropertyChanging("id_bebida_fk");
                    _id_bebida_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bebida_fk");
                    Onid_bebida_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_bebida_fk;
        partial void Onid_bebida_fkChanging(global::System.Int32 value);
        partial void Onid_bebida_fkChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_venta_fk
        {
            get
            {
                return _id_venta_fk;
            }
            set
            {
                if (_id_venta_fk != value)
                {
                    Onid_venta_fkChanging(value);
                    ReportPropertyChanging("id_venta_fk");
                    _id_venta_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_venta_fk");
                    Onid_venta_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_venta_fk;
        partial void Onid_venta_fkChanging(global::System.Int32 value);
        partial void Onid_venta_fkChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_detalle_venta_Bebida", "Bebida")]
        public Bebidas Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebidas>("DAL.FK_detalle_venta_Bebida", "Bebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebidas>("DAL.FK_detalle_venta_Bebida", "Bebida").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bebidas> BebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebidas>("DAL.FK_detalle_venta_Bebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bebidas>("DAL.FK_detalle_venta_Bebida", "Bebida", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_detalle_venta_Venta", "Venta")]
        public Venta Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("DAL.FK_detalle_venta_Venta", "Venta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("DAL.FK_detalle_venta_Venta", "Venta").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venta> VentaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("DAL.FK_detalle_venta_Venta", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venta>("DAL.FK_detalle_venta_Venta", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="MarcaBebida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MarcaBebida : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto MarcaBebida.
        /// </summary>
        /// <param name="id_marca">Valor inicial de la propiedad id_marca.</param>
        /// <param name="marca">Valor inicial de la propiedad marca.</param>
        public static MarcaBebida CreateMarcaBebida(global::System.Int32 id_marca, global::System.String marca)
        {
            MarcaBebida marcaBebida = new MarcaBebida();
            marcaBebida.id_marca = id_marca;
            marcaBebida.marca = marca;
            return marcaBebida;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_marca
        {
            get
            {
                return _id_marca;
            }
            set
            {
                if (_id_marca != value)
                {
                    Onid_marcaChanging(value);
                    ReportPropertyChanging("id_marca");
                    _id_marca = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_marca");
                    Onid_marcaChanged();
                }
            }
        }
        private global::System.Int32 _id_marca;
        partial void Onid_marcaChanging(global::System.Int32 value);
        partial void Onid_marcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.String _marca;
        partial void OnmarcaChanging(global::System.String value);
        partial void OnmarcaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_Bebida_MarcaBebida", "Bebida")]
        public EntityCollection<Bebidas> Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bebidas>("DAL.FK_Bebida_MarcaBebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bebidas>("DAL.FK_Bebida_MarcaBebida", "Bebida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="TipoBebida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoBebida : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto TipoBebida.
        /// </summary>
        /// <param name="id_tipo">Valor inicial de la propiedad id_tipo.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        public static TipoBebida CreateTipoBebida(global::System.Int32 id_tipo, global::System.String tipo)
        {
            TipoBebida tipoBebida = new TipoBebida();
            tipoBebida.id_tipo = id_tipo;
            tipoBebida.tipo = tipo;
            return tipoBebida;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tipo
        {
            get
            {
                return _id_tipo;
            }
            set
            {
                if (_id_tipo != value)
                {
                    Onid_tipoChanging(value);
                    ReportPropertyChanging("id_tipo");
                    _id_tipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tipo");
                    Onid_tipoChanged();
                }
            }
        }
        private global::System.Int32 _id_tipo;
        partial void Onid_tipoChanging(global::System.Int32 value);
        partial void Onid_tipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_Bebida_TipoBebida", "Bebida")]
        public EntityCollection<Bebidas> Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Bebidas>("DAL.FK_Bebida_TipoBebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Bebidas>("DAL.FK_Bebida_TipoBebida", "Bebida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="id_usuario">Valor inicial de la propiedad id_usuario.</param>
        /// <param name="nombre_usuario">Valor inicial de la propiedad nombre_usuario.</param>
        /// <param name="contrasenja_usuario">Valor inicial de la propiedad contrasenja_usuario.</param>
        /// <param name="esAdministrador">Valor inicial de la propiedad esAdministrador.</param>
        public static Usuario CreateUsuario(global::System.Int32 id_usuario, global::System.String nombre_usuario, global::System.String contrasenja_usuario, global::System.Boolean esAdministrador)
        {
            Usuario usuario = new Usuario();
            usuario.id_usuario = id_usuario;
            usuario.nombre_usuario = nombre_usuario;
            usuario.contrasenja_usuario = contrasenja_usuario;
            usuario.esAdministrador = esAdministrador;
            return usuario;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_usuario
        {
            get
            {
                return _nombre_usuario;
            }
            set
            {
                Onnombre_usuarioChanging(value);
                ReportPropertyChanging("nombre_usuario");
                _nombre_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_usuario");
                Onnombre_usuarioChanged();
            }
        }
        private global::System.String _nombre_usuario;
        partial void Onnombre_usuarioChanging(global::System.String value);
        partial void Onnombre_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasenja_usuario
        {
            get
            {
                return _contrasenja_usuario;
            }
            set
            {
                Oncontrasenja_usuarioChanging(value);
                ReportPropertyChanging("contrasenja_usuario");
                _contrasenja_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasenja_usuario");
                Oncontrasenja_usuarioChanged();
            }
        }
        private global::System.String _contrasenja_usuario;
        partial void Oncontrasenja_usuarioChanging(global::System.String value);
        partial void Oncontrasenja_usuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean esAdministrador
        {
            get
            {
                return _esAdministrador;
            }
            set
            {
                OnesAdministradorChanging(value);
                ReportPropertyChanging("esAdministrador");
                _esAdministrador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("esAdministrador");
                OnesAdministradorChanged();
            }
        }
        private global::System.Boolean _esAdministrador;
        partial void OnesAdministradorChanging(global::System.Boolean value);
        partial void OnesAdministradorChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_Venta_Usuario", "Venta")]
        public EntityCollection<Venta> Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("DAL.FK_Venta_Usuario", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("DAL.FK_Venta_Usuario", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DAL", Name="Venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Venta.
        /// </summary>
        /// <param name="id_venta">Valor inicial de la propiedad id_venta.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="total_precio">Valor inicial de la propiedad total_precio.</param>
        /// <param name="id_usuario_fk">Valor inicial de la propiedad id_usuario_fk.</param>
        public static Venta CreateVenta(global::System.Int32 id_venta, global::System.DateTime fecha, global::System.Decimal total_precio, global::System.Int32 id_usuario_fk)
        {
            Venta venta = new Venta();
            venta.id_venta = id_venta;
            venta.fecha = fecha;
            venta.total_precio = total_precio;
            venta.id_usuario_fk = id_usuario_fk;
            return venta;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_venta
        {
            get
            {
                return _id_venta;
            }
            set
            {
                if (_id_venta != value)
                {
                    Onid_ventaChanging(value);
                    ReportPropertyChanging("id_venta");
                    _id_venta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_venta");
                    Onid_ventaChanged();
                }
            }
        }
        private global::System.Int32 _id_venta;
        partial void Onid_ventaChanging(global::System.Int32 value);
        partial void Onid_ventaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal total_precio
        {
            get
            {
                return _total_precio;
            }
            set
            {
                Ontotal_precioChanging(value);
                ReportPropertyChanging("total_precio");
                _total_precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_precio");
                Ontotal_precioChanged();
            }
        }
        private global::System.Decimal _total_precio;
        partial void Ontotal_precioChanging(global::System.Decimal value);
        partial void Ontotal_precioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario_fk
        {
            get
            {
                return _id_usuario_fk;
            }
            set
            {
                Onid_usuario_fkChanging(value);
                ReportPropertyChanging("id_usuario_fk");
                _id_usuario_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_fk");
                Onid_usuario_fkChanged();
            }
        }
        private global::System.Int32 _id_usuario_fk;
        partial void Onid_usuario_fkChanging(global::System.Int32 value);
        partial void Onid_usuario_fkChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_detalle_venta_Venta", "detalle_venta")]
        public EntityCollection<detalle_venta> detalle_venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalle_venta>("DAL.FK_detalle_venta_Venta", "detalle_venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalle_venta>("DAL.FK_detalle_venta_Venta", "detalle_venta", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DAL", "FK_Venta_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DAL.FK_Venta_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DAL.FK_Venta_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("DAL.FK_Venta_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("DAL.FK_Venta_Usuario", "Usuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
