//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_Bebida_MarcaBebida", "MarcaBebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.MarcaBebida), "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.EntidadBebida), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_Bebida_TipoBebida", "TipoBebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.TipoBebida), "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.EntidadBebida), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_detalle_venta_Bebida", "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.EntidadBebida), "detalle_venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.detalle_venta), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_DetalleBodegaLocal_Bebida", "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.EntidadBebida), "DetalleBodegaLocal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.DetalleEnBodega), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_DetalleBodegaLocal_Bodega", "Bodega", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.EntidadBodega), "DetalleBodegaLocal", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.DetalleEnBodega), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_detalle_venta_Venta", "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Venta), "detalle_venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.detalle_venta), true)]
[assembly: EdmRelationshipAttribute("WebBotilleriaModel", "FK_Venta_Usuario", "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Data_Access_Layer.Usuario), "Venta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Data_Access_Layer.Venta), true)]

#endregion

namespace Data_Access_Layer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class WebBotilleriaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new WebBotilleriaEntities object using the connection string found in the 'WebBotilleriaEntities' section of the application configuration file.
        /// </summary>
        public WebBotilleriaEntities() : base("name=WebBotilleriaEntities", "WebBotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebBotilleriaEntities object.
        /// </summary>
        public WebBotilleriaEntities(string connectionString) : base(connectionString, "WebBotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new WebBotilleriaEntities object.
        /// </summary>
        public WebBotilleriaEntities(EntityConnection connection) : base(connection, "WebBotilleriaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntidadBebida> Bebidas
        {
            get
            {
                if ((_Bebidas == null))
                {
                    _Bebidas = base.CreateObjectSet<EntidadBebida>("Bebidas");
                }
                return _Bebidas;
            }
        }
        private ObjectSet<EntidadBebida> _Bebidas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EntidadBodega> Bodegas
        {
            get
            {
                if ((_Bodegas == null))
                {
                    _Bodegas = base.CreateObjectSet<EntidadBodega>("Bodegas");
                }
                return _Bodegas;
            }
        }
        private ObjectSet<EntidadBodega> _Bodegas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<detalle_venta> detalle_venta
        {
            get
            {
                if ((_detalle_venta == null))
                {
                    _detalle_venta = base.CreateObjectSet<detalle_venta>("detalle_venta");
                }
                return _detalle_venta;
            }
        }
        private ObjectSet<detalle_venta> _detalle_venta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DetalleEnBodega> DetalleBodegaLocals
        {
            get
            {
                if ((_DetalleBodegaLocals == null))
                {
                    _DetalleBodegaLocals = base.CreateObjectSet<DetalleEnBodega>("DetalleBodegaLocals");
                }
                return _DetalleBodegaLocals;
            }
        }
        private ObjectSet<DetalleEnBodega> _DetalleBodegaLocals;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MarcaBebida> MarcaBebidas
        {
            get
            {
                if ((_MarcaBebidas == null))
                {
                    _MarcaBebidas = base.CreateObjectSet<MarcaBebida>("MarcaBebidas");
                }
                return _MarcaBebidas;
            }
        }
        private ObjectSet<MarcaBebida> _MarcaBebidas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TipoBebida> TipoBebidas
        {
            get
            {
                if ((_TipoBebidas == null))
                {
                    _TipoBebidas = base.CreateObjectSet<TipoBebida>("TipoBebidas");
                }
                return _TipoBebidas;
            }
        }
        private ObjectSet<TipoBebida> _TipoBebidas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Usuario> Usuarios
        {
            get
            {
                if ((_Usuarios == null))
                {
                    _Usuarios = base.CreateObjectSet<Usuario>("Usuarios");
                }
                return _Usuarios;
            }
        }
        private ObjectSet<Usuario> _Usuarios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Venta> Ventas
        {
            get
            {
                if ((_Ventas == null))
                {
                    _Ventas = base.CreateObjectSet<Venta>("Ventas");
                }
                return _Ventas;
            }
        }
        private ObjectSet<Venta> _Ventas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bebidas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBebidas(EntidadBebida entidadBebida)
        {
            base.AddObject("Bebidas", entidadBebida);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bodegas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBodegas(EntidadBodega entidadBodega)
        {
            base.AddObject("Bodegas", entidadBodega);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the detalle_venta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodetalle_venta(detalle_venta detalle_venta)
        {
            base.AddObject("detalle_venta", detalle_venta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DetalleBodegaLocals EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDetalleBodegaLocals(DetalleEnBodega detalleEnBodega)
        {
            base.AddObject("DetalleBodegaLocals", detalleEnBodega);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MarcaBebidas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarcaBebidas(MarcaBebida marcaBebida)
        {
            base.AddObject("MarcaBebidas", marcaBebida);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TipoBebidas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTipoBebidas(TipoBebida tipoBebida)
        {
            base.AddObject("TipoBebidas", tipoBebida);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Usuarios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsuarios(Usuario usuario)
        {
            base.AddObject("Usuarios", usuario);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ventas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVentas(Venta venta)
        {
            base.AddObject("Ventas", venta);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="detalle_venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class detalle_venta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new detalle_venta object.
        /// </summary>
        /// <param name="cantidad">Initial value of the cantidad property.</param>
        /// <param name="id_bebida_fk">Initial value of the id_bebida_fk property.</param>
        /// <param name="id_venta_fk">Initial value of the id_venta_fk property.</param>
        public static detalle_venta Createdetalle_venta(global::System.Int32 cantidad, global::System.Int32 id_bebida_fk, global::System.Int32 id_venta_fk)
        {
            detalle_venta detalle_venta = new detalle_venta();
            detalle_venta.cantidad = cantidad;
            detalle_venta.id_bebida_fk = id_bebida_fk;
            detalle_venta.id_venta_fk = id_venta_fk;
            return detalle_venta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bebida_fk
        {
            get
            {
                return _id_bebida_fk;
            }
            set
            {
                if (_id_bebida_fk != value)
                {
                    Onid_bebida_fkChanging(value);
                    ReportPropertyChanging("id_bebida_fk");
                    _id_bebida_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bebida_fk");
                    Onid_bebida_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_bebida_fk;
        partial void Onid_bebida_fkChanging(global::System.Int32 value);
        partial void Onid_bebida_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_venta_fk
        {
            get
            {
                return _id_venta_fk;
            }
            set
            {
                if (_id_venta_fk != value)
                {
                    Onid_venta_fkChanging(value);
                    ReportPropertyChanging("id_venta_fk");
                    _id_venta_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_venta_fk");
                    Onid_venta_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_venta_fk;
        partial void Onid_venta_fkChanging(global::System.Int32 value);
        partial void Onid_venta_fkChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Bebida", "Bebida")]
        public EntidadBebida Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntidadBebida> BebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_detalle_venta_Bebida", "Bebida", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Venta", "Venta")]
        public Venta Venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta", "Venta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta", "Venta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Venta> VentaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Venta>("WebBotilleriaModel.FK_detalle_venta_Venta", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="DetalleEnBodega")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleEnBodega : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DetalleEnBodega object.
        /// </summary>
        /// <param name="id_bodega_fk">Initial value of the id_bodega_fk property.</param>
        /// <param name="id_bebida_fk">Initial value of the id_bebida_fk property.</param>
        /// <param name="cantidad">Initial value of the cantidad property.</param>
        public static DetalleEnBodega CreateDetalleEnBodega(global::System.Int32 id_bodega_fk, global::System.Int32 id_bebida_fk, global::System.Int32 cantidad)
        {
            DetalleEnBodega detalleEnBodega = new DetalleEnBodega();
            detalleEnBodega.id_bodega_fk = id_bodega_fk;
            detalleEnBodega.id_bebida_fk = id_bebida_fk;
            detalleEnBodega.cantidad = cantidad;
            return detalleEnBodega;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega_fk
        {
            get
            {
                return _id_bodega_fk;
            }
            set
            {
                if (_id_bodega_fk != value)
                {
                    Onid_bodega_fkChanging(value);
                    ReportPropertyChanging("id_bodega_fk");
                    _id_bodega_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bodega_fk");
                    Onid_bodega_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_bodega_fk;
        partial void Onid_bodega_fkChanging(global::System.Int32 value);
        partial void Onid_bodega_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bebida_fk
        {
            get
            {
                return _id_bebida_fk;
            }
            set
            {
                if (_id_bebida_fk != value)
                {
                    Onid_bebida_fkChanging(value);
                    ReportPropertyChanging("id_bebida_fk");
                    _id_bebida_fk = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bebida_fk");
                    Onid_bebida_fkChanged();
                }
            }
        }
        private global::System.Int32 _id_bebida_fk;
        partial void Onid_bebida_fkChanging(global::System.Int32 value);
        partial void Onid_bebida_fkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidad
        {
            get
            {
                return _cantidad;
            }
            set
            {
                if (_cantidad != value)
                {
                    OncantidadChanging(value);
                    ReportPropertyChanging("cantidad");
                    _cantidad = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("cantidad");
                    OncantidadChanged();
                }
            }
        }
        private global::System.Int32 _cantidad;
        partial void OncantidadChanging(global::System.Int32 value);
        partial void OncantidadChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_DetalleBodegaLocal_Bebida", "Bebida")]
        public EntidadBebida Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bebida", "Bebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bebida", "Bebida").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntidadBebida> BebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntidadBebida>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bebida", "Bebida", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_DetalleBodegaLocal_Bodega", "Bodega")]
        public EntidadBodega Bodega
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bodega", "Bodega").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bodega", "Bodega").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<EntidadBodega> BodegaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<EntidadBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bodega", "Bodega");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<EntidadBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bodega", "Bodega", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="EntidadBebida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntidadBebida : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntidadBebida object.
        /// </summary>
        /// <param name="id_bebida">Initial value of the id_bebida property.</param>
        /// <param name="nombre_producto">Initial value of the nombre_producto property.</param>
        /// <param name="precio">Initial value of the precio property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        /// <param name="grados_alcohol">Initial value of the grados_alcohol property.</param>
        /// <param name="volumen_litros">Initial value of the volumen_litros property.</param>
        /// <param name="es_retornable">Initial value of the es_retornable property.</param>
        /// <param name="comentario">Initial value of the comentario property.</param>
        /// <param name="marca">Initial value of the marca property.</param>
        public static EntidadBebida CreateEntidadBebida(global::System.Int32 id_bebida, global::System.String nombre_producto, global::System.Single precio, global::System.Int32 tipo, global::System.Single grados_alcohol, global::System.Single volumen_litros, global::System.Boolean es_retornable, global::System.String comentario, global::System.Int32 marca)
        {
            EntidadBebida entidadBebida = new EntidadBebida();
            entidadBebida.id_bebida = id_bebida;
            entidadBebida.nombre_producto = nombre_producto;
            entidadBebida.precio = precio;
            entidadBebida.tipo = tipo;
            entidadBebida.grados_alcohol = grados_alcohol;
            entidadBebida.volumen_litros = volumen_litros;
            entidadBebida.es_retornable = es_retornable;
            entidadBebida.comentario = comentario;
            entidadBebida.marca = marca;
            return entidadBebida;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bebida
        {
            get
            {
                return _id_bebida;
            }
            set
            {
                if (_id_bebida != value)
                {
                    Onid_bebidaChanging(value);
                    ReportPropertyChanging("id_bebida");
                    _id_bebida = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bebida");
                    Onid_bebidaChanged();
                }
            }
        }
        private global::System.Int32 _id_bebida;
        partial void Onid_bebidaChanging(global::System.Int32 value);
        partial void Onid_bebidaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_producto
        {
            get
            {
                return _nombre_producto;
            }
            set
            {
                Onnombre_productoChanging(value);
                ReportPropertyChanging("nombre_producto");
                _nombre_producto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_producto");
                Onnombre_productoChanged();
            }
        }
        private global::System.String _nombre_producto;
        partial void Onnombre_productoChanging(global::System.String value);
        partial void Onnombre_productoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Single _precio;
        partial void OnprecioChanging(global::System.Single value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.Int32 _tipo;
        partial void OntipoChanging(global::System.Int32 value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single grados_alcohol
        {
            get
            {
                return _grados_alcohol;
            }
            set
            {
                Ongrados_alcoholChanging(value);
                ReportPropertyChanging("grados_alcohol");
                _grados_alcohol = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("grados_alcohol");
                Ongrados_alcoholChanged();
            }
        }
        private global::System.Single _grados_alcohol;
        partial void Ongrados_alcoholChanging(global::System.Single value);
        partial void Ongrados_alcoholChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Single volumen_litros
        {
            get
            {
                return _volumen_litros;
            }
            set
            {
                Onvolumen_litrosChanging(value);
                ReportPropertyChanging("volumen_litros");
                _volumen_litros = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("volumen_litros");
                Onvolumen_litrosChanged();
            }
        }
        private global::System.Single _volumen_litros;
        partial void Onvolumen_litrosChanging(global::System.Single value);
        partial void Onvolumen_litrosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean es_retornable
        {
            get
            {
                return _es_retornable;
            }
            set
            {
                Ones_retornableChanging(value);
                ReportPropertyChanging("es_retornable");
                _es_retornable = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("es_retornable");
                Ones_retornableChanged();
            }
        }
        private global::System.Boolean _es_retornable;
        partial void Ones_retornableChanging(global::System.Boolean value);
        partial void Ones_retornableChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comentario
        {
            get
            {
                return _comentario;
            }
            set
            {
                OncomentarioChanging(value);
                ReportPropertyChanging("comentario");
                _comentario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comentario");
                OncomentarioChanged();
            }
        }
        private global::System.String _comentario;
        partial void OncomentarioChanging(global::System.String value);
        partial void OncomentarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.Int32 _marca;
        partial void OnmarcaChanging(global::System.Int32 value);
        partial void OnmarcaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Bebida_MarcaBebida", "MarcaBebida")]
        public MarcaBebida MarcaBebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MarcaBebida>("WebBotilleriaModel.FK_Bebida_MarcaBebida", "MarcaBebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MarcaBebida>("WebBotilleriaModel.FK_Bebida_MarcaBebida", "MarcaBebida").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MarcaBebida> MarcaBebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MarcaBebida>("WebBotilleriaModel.FK_Bebida_MarcaBebida", "MarcaBebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MarcaBebida>("WebBotilleriaModel.FK_Bebida_MarcaBebida", "MarcaBebida", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Bebida_TipoBebida", "TipoBebida")]
        public TipoBebida TipoBebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoBebida>("WebBotilleriaModel.FK_Bebida_TipoBebida", "TipoBebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoBebida>("WebBotilleriaModel.FK_Bebida_TipoBebida", "TipoBebida").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TipoBebida> TipoBebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TipoBebida>("WebBotilleriaModel.FK_Bebida_TipoBebida", "TipoBebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TipoBebida>("WebBotilleriaModel.FK_Bebida_TipoBebida", "TipoBebida", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Bebida", "detalle_venta")]
        public EntityCollection<detalle_venta> detalle_venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Bebida", "detalle_venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Bebida", "detalle_venta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_DetalleBodegaLocal_Bebida", "DetalleBodegaLocal")]
        public EntityCollection<DetalleEnBodega> DetalleBodegaLocals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleEnBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bebida", "DetalleBodegaLocal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleEnBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bebida", "DetalleBodegaLocal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="EntidadBodega")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EntidadBodega : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EntidadBodega object.
        /// </summary>
        /// <param name="id_bodega">Initial value of the id_bodega property.</param>
        /// <param name="nombre_bodega">Initial value of the nombre_bodega property.</param>
        /// <param name="direccion">Initial value of the direccion property.</param>
        /// <param name="telefono">Initial value of the telefono property.</param>
        /// <param name="correo_electronico">Initial value of the correo_electronico property.</param>
        public static EntidadBodega CreateEntidadBodega(global::System.Int32 id_bodega, global::System.String nombre_bodega, global::System.String direccion, global::System.Int32 telefono, global::System.String correo_electronico)
        {
            EntidadBodega entidadBodega = new EntidadBodega();
            entidadBodega.id_bodega = id_bodega;
            entidadBodega.nombre_bodega = nombre_bodega;
            entidadBodega.direccion = direccion;
            entidadBodega.telefono = telefono;
            entidadBodega.correo_electronico = correo_electronico;
            return entidadBodega;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_bodega
        {
            get
            {
                return _id_bodega;
            }
            set
            {
                if (_id_bodega != value)
                {
                    Onid_bodegaChanging(value);
                    ReportPropertyChanging("id_bodega");
                    _id_bodega = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_bodega");
                    Onid_bodegaChanged();
                }
            }
        }
        private global::System.Int32 _id_bodega;
        partial void Onid_bodegaChanging(global::System.Int32 value);
        partial void Onid_bodegaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_bodega
        {
            get
            {
                return _nombre_bodega;
            }
            set
            {
                Onnombre_bodegaChanging(value);
                ReportPropertyChanging("nombre_bodega");
                _nombre_bodega = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_bodega");
                Onnombre_bodegaChanged();
            }
        }
        private global::System.String _nombre_bodega;
        partial void Onnombre_bodegaChanging(global::System.String value);
        partial void Onnombre_bodegaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.Int32 _telefono;
        partial void OntelefonoChanging(global::System.Int32 value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correo_electronico
        {
            get
            {
                return _correo_electronico;
            }
            set
            {
                Oncorreo_electronicoChanging(value);
                ReportPropertyChanging("correo_electronico");
                _correo_electronico = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("correo_electronico");
                Oncorreo_electronicoChanged();
            }
        }
        private global::System.String _correo_electronico;
        partial void Oncorreo_electronicoChanging(global::System.String value);
        partial void Oncorreo_electronicoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_DetalleBodegaLocal_Bodega", "DetalleBodegaLocal")]
        public EntityCollection<DetalleEnBodega> DetalleBodegaLocals
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleEnBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bodega", "DetalleBodegaLocal");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleEnBodega>("WebBotilleriaModel.FK_DetalleBodegaLocal_Bodega", "DetalleBodegaLocal", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="MarcaBebida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MarcaBebida : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MarcaBebida object.
        /// </summary>
        /// <param name="id_marca">Initial value of the id_marca property.</param>
        /// <param name="marca">Initial value of the marca property.</param>
        public static MarcaBebida CreateMarcaBebida(global::System.Int32 id_marca, global::System.String marca)
        {
            MarcaBebida marcaBebida = new MarcaBebida();
            marcaBebida.id_marca = id_marca;
            marcaBebida.marca = marca;
            return marcaBebida;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_marca
        {
            get
            {
                return _id_marca;
            }
            set
            {
                if (_id_marca != value)
                {
                    Onid_marcaChanging(value);
                    ReportPropertyChanging("id_marca");
                    _id_marca = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_marca");
                    Onid_marcaChanged();
                }
            }
        }
        private global::System.Int32 _id_marca;
        partial void Onid_marcaChanging(global::System.Int32 value);
        partial void Onid_marcaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.String _marca;
        partial void OnmarcaChanging(global::System.String value);
        partial void OnmarcaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Bebida_MarcaBebida", "Bebida")]
        public EntityCollection<EntidadBebida> Bebidas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntidadBebida>("WebBotilleriaModel.FK_Bebida_MarcaBebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntidadBebida>("WebBotilleriaModel.FK_Bebida_MarcaBebida", "Bebida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="TipoBebida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TipoBebida : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TipoBebida object.
        /// </summary>
        /// <param name="id_tipo">Initial value of the id_tipo property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        public static TipoBebida CreateTipoBebida(global::System.Int32 id_tipo, global::System.String tipo)
        {
            TipoBebida tipoBebida = new TipoBebida();
            tipoBebida.id_tipo = id_tipo;
            tipoBebida.tipo = tipo;
            return tipoBebida;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_tipo
        {
            get
            {
                return _id_tipo;
            }
            set
            {
                if (_id_tipo != value)
                {
                    Onid_tipoChanging(value);
                    ReportPropertyChanging("id_tipo");
                    _id_tipo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_tipo");
                    Onid_tipoChanged();
                }
            }
        }
        private global::System.Int32 _id_tipo;
        partial void Onid_tipoChanging(global::System.Int32 value);
        partial void Onid_tipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Bebida_TipoBebida", "Bebida")]
        public EntityCollection<EntidadBebida> Bebidas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<EntidadBebida>("WebBotilleriaModel.FK_Bebida_TipoBebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<EntidadBebida>("WebBotilleriaModel.FK_Bebida_TipoBebida", "Bebida", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Usuario object.
        /// </summary>
        /// <param name="id_usuario">Initial value of the id_usuario property.</param>
        /// <param name="nombre_usuario">Initial value of the nombre_usuario property.</param>
        /// <param name="contrasenja_usuario">Initial value of the contrasenja_usuario property.</param>
        /// <param name="esAdministrador">Initial value of the esAdministrador property.</param>
        public static Usuario CreateUsuario(global::System.Int32 id_usuario, global::System.String nombre_usuario, global::System.String contrasenja_usuario, global::System.Boolean esAdministrador)
        {
            Usuario usuario = new Usuario();
            usuario.id_usuario = id_usuario;
            usuario.nombre_usuario = nombre_usuario;
            usuario.contrasenja_usuario = contrasenja_usuario;
            usuario.esAdministrador = esAdministrador;
            return usuario;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre_usuario
        {
            get
            {
                return _nombre_usuario;
            }
            set
            {
                Onnombre_usuarioChanging(value);
                ReportPropertyChanging("nombre_usuario");
                _nombre_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre_usuario");
                Onnombre_usuarioChanged();
            }
        }
        private global::System.String _nombre_usuario;
        partial void Onnombre_usuarioChanging(global::System.String value);
        partial void Onnombre_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String contrasenja_usuario
        {
            get
            {
                return _contrasenja_usuario;
            }
            set
            {
                Oncontrasenja_usuarioChanging(value);
                ReportPropertyChanging("contrasenja_usuario");
                _contrasenja_usuario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("contrasenja_usuario");
                Oncontrasenja_usuarioChanged();
            }
        }
        private global::System.String _contrasenja_usuario;
        partial void Oncontrasenja_usuarioChanging(global::System.String value);
        partial void Oncontrasenja_usuarioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean esAdministrador
        {
            get
            {
                return _esAdministrador;
            }
            set
            {
                OnesAdministradorChanging(value);
                ReportPropertyChanging("esAdministrador");
                _esAdministrador = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("esAdministrador");
                OnesAdministradorChanged();
            }
        }
        private global::System.Boolean _esAdministrador;
        partial void OnesAdministradorChanging(global::System.Boolean value);
        partial void OnesAdministradorChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Venta_Usuario", "Venta")]
        public EntityCollection<Venta> Ventas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Venta>("WebBotilleriaModel.FK_Venta_Usuario", "Venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Venta>("WebBotilleriaModel.FK_Venta_Usuario", "Venta", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebBotilleriaModel", Name="Venta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Venta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Venta object.
        /// </summary>
        /// <param name="id_venta">Initial value of the id_venta property.</param>
        /// <param name="fecha">Initial value of the fecha property.</param>
        /// <param name="total_precio">Initial value of the total_precio property.</param>
        /// <param name="id_usuario_fk">Initial value of the id_usuario_fk property.</param>
        public static Venta CreateVenta(global::System.Int32 id_venta, global::System.DateTime fecha, global::System.Decimal total_precio, global::System.Int32 id_usuario_fk)
        {
            Venta venta = new Venta();
            venta.id_venta = id_venta;
            venta.fecha = fecha;
            venta.total_precio = total_precio;
            venta.id_usuario_fk = id_usuario_fk;
            return venta;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_venta
        {
            get
            {
                return _id_venta;
            }
            set
            {
                if (_id_venta != value)
                {
                    Onid_ventaChanging(value);
                    ReportPropertyChanging("id_venta");
                    _id_venta = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_venta");
                    Onid_ventaChanged();
                }
            }
        }
        private global::System.Int32 _id_venta;
        partial void Onid_ventaChanging(global::System.Int32 value);
        partial void Onid_ventaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.DateTime _fecha;
        partial void OnfechaChanging(global::System.DateTime value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal total_precio
        {
            get
            {
                return _total_precio;
            }
            set
            {
                Ontotal_precioChanging(value);
                ReportPropertyChanging("total_precio");
                _total_precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("total_precio");
                Ontotal_precioChanged();
            }
        }
        private global::System.Decimal _total_precio;
        partial void Ontotal_precioChanging(global::System.Decimal value);
        partial void Ontotal_precioChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario_fk
        {
            get
            {
                return _id_usuario_fk;
            }
            set
            {
                Onid_usuario_fkChanging(value);
                ReportPropertyChanging("id_usuario_fk");
                _id_usuario_fk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_usuario_fk");
                Onid_usuario_fkChanged();
            }
        }
        private global::System.Int32 _id_usuario_fk;
        partial void Onid_usuario_fkChanging(global::System.Int32 value);
        partial void Onid_usuario_fkChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_detalle_venta_Venta", "detalle_venta")]
        public EntityCollection<detalle_venta> detalle_venta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Venta", "detalle_venta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<detalle_venta>("WebBotilleriaModel.FK_detalle_venta_Venta", "detalle_venta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("WebBotilleriaModel", "FK_Venta_Usuario", "Usuario")]
        public Usuario Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Usuario> UsuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Usuario>("WebBotilleriaModel.FK_Venta_Usuario", "Usuario", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
